spring:
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/bootrentaldb
    username: reho
    password: djtommy
  liquibase:
    change-log: classpath:db/changelog/changelog.sql